package pojo;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.UID
     *
     * @mbg.generated
     */
    private Integer UID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USERNAME
     *
     * @mbg.generated
     */
    private String USERNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWORD
     *
     * @mbg.generated
     */
    private String PASSWORD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.AUTHORITY
     *
     * @mbg.generated
     */
    private Integer AUTHORITY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.NICKNAME
     *
     * @mbg.generated
     */
    private String NICKNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.AGE
     *
     * @mbg.generated
     */
    private Integer AGE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GENDER
     *
     * @mbg.generated
     */
    private String GENDER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PHONE
     *
     * @mbg.generated
     */
    private String PHONE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ADDRESS
     *
     * @mbg.generated
     */
    private String ADDRESS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.UID
     *
     * @return the value of USER.UID
     *
     * @mbg.generated
     */
    public Integer getUID() {
        return UID;

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.UID
     *
     * @param UID the value for USER.UID
     *
     * @mbg.generated
     */
    public void setUID(Integer UID) {
        this.UID = UID;

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USERNAME
     *
     * @return the value of USER.USERNAME
     *
     * @mbg.generated
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USERNAME
     *
     * @param USERNAME the value for USER.USERNAME
     *
     * @mbg.generated
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME == null ? null : USERNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PASSWORD
     *
     * @return the value of USER.PASSWORD
     *
     * @mbg.generated
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PASSWORD
     *
     * @param PASSWORD the value for USER.PASSWORD
     *
     * @mbg.generated
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.AUTHORITY
     *
     * @return the value of USER.AUTHORITY
     *
     * @mbg.generated
     */
    public Integer getAUTHORITY() {
        return AUTHORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.AUTHORITY
     *
     * @param AUTHORITY the value for USER.AUTHORITY
     *
     * @mbg.generated
     */
    public void setAUTHORITY(Integer AUTHORITY) {
        this.AUTHORITY = AUTHORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.NICKNAME
     *
     * @return the value of USER.NICKNAME
     *
     * @mbg.generated
     */
    public String getNICKNAME() {
        return NICKNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.NICKNAME
     *
     * @param NICKNAME the value for USER.NICKNAME
     *
     * @mbg.generated
     */
    public void setNICKNAME(String NICKNAME) {
        this.NICKNAME = NICKNAME == null ? null : NICKNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.AGE
     *
     * @return the value of USER.AGE
     *
     * @mbg.generated
     */
    public Integer getAGE() {
        return AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.AGE
     *
     * @param AGE the value for USER.AGE
     *
     * @mbg.generated
     */
    public void setAGE(Integer AGE) {
        this.AGE = AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.GENDER
     *
     * @return the value of USER.GENDER
     *
     * @mbg.generated
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.GENDER
     *
     * @param GENDER the value for USER.GENDER
     *
     * @mbg.generated
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER == null ? null : GENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PHONE
     *
     * @return the value of USER.PHONE
     *
     * @mbg.generated
     */
    public String getPHONE() {
        return PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PHONE
     *
     * @param PHONE the value for USER.PHONE
     *
     * @mbg.generated
     */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE == null ? null : PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ADDRESS
     *
     * @return the value of USER.ADDRESS
     *
     * @mbg.generated
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ADDRESS
     *
     * @param ADDRESS the value for USER.ADDRESS
     *
     * @mbg.generated
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }
}